language: php
  
env:
  global:
    - PLUGIN_NAME=Environment
    - PLUGIN_PATH=Plugin/Environment
    - REQUIRE=""
    - DB=mysql
    - CAKE_VERSION=2.5

matrix:
  include:
    - php: 5.5
      env:
        - PHPCS=1
    - php: 5.5
      env:
        - FOC_VALIDATE=1

before_script:
  - git clone https://github.com/imsamurai/travis.git --depth 1 ../travis
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: im.samuray@gmail.com
